
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mini_twitter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - JWT_SECRET=sua-chave-secreta-aqui
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/mini_twitter
    restart: always

volumes:
  postgres_data:

